name: Run Python Tests

on:
  push:
    branches:
      - master
      - continuous_integration
  pull_request:
    branches:
      - master
      - continuous_integration

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - name: Install dependencies
        run: |
          conda env create -f environment.yaml
      - name: Run tests with pytest
        run: pytest
